### ISSUE TITLE
Next WG Meeting

### ISSUE THREAD

**Issue by yunong** [nodejs/post-mortem#12]
It's been a while since our last WG meeting. Anyone opposed to setting up a new one? I know @indutny has been working on some interesting post mortem work with github.com/indutny/llnode for Linux. I'd like to talk about next steps in terms of making mdb_v8 more broadly available on different platforms.

cc @davepacheco @jclulow @lucamaraschi

**Comment by misterdjules** [comment]
@yunong I'm in too.

**Comment by lucamaraschi** [comment]
@yunong definitely in! ;-)
I would like to add to the discussion point a more broader overview and "vision" of how we could evolve post-mortem to cross platforms and especially improve/evolve developer and operation experience.

**Comment by indutny** [comment]
I'm in too.

**Comment by bmeck** [comment]
I'm more in JSON snapshot land, but I can join in.

**Comment by yunong** [comment]
Great, seeing as it's close to the Holidays, I'll send out a doodle for the new year in a little bit.

**Comment by davepacheco** [comment]
I'm in.

In terms of topics for discussion: the goals of the WG that we outlined in earlier meetings were:

> to elevate the role of postmortem debugging for Node, to assist in the development of techniques and tools, and to make techniques and tools known and available to Node.js users.

(from README.md).  I've said that I think our goal should be to encourage the efforts of the _several_ different projects working on postmortem tools for Node and to do any work that's truly common to many of them (e.g., collecting use-cases and managing the metadata stored in V8/Node itself).  I _don't_ think we should be trying to pick (or work on) a One True Tool for Node postmortem debugging because I don't think there's a tool that can meet all of our needs -- the use-cases are overlapping, but also conflicting.  It seemed to me that people agreed with this, but I don't want to assume anything or put words in anybody's mouth.  If people do agree, I think it's worth calling this out in the mission.

And if that's true, I think the most useful next pieces of work for the WG remain:
- putting together a list of tools out there and what they're capable of (#6), which hopefully could wind up in the official Node docs
- putting together a list of use-cases for postmortem debugging (#7), which I also hope could wind up in the official Node docs
- putting together a collection of concrete analyses from real-world issues to inform the development of all these tools (partially covered by #11)

I'd like to talk about moving mdb_v8 forward, too, but I'm reluctant to use the WG to focus on the tactical development work of one of the many tools out there.

**Comment by lucamaraschi** [comment]
@yunong any idea of when we should gather all together again?

**Comment by yunong** [comment]
Here's the doodle poll for the next meeting. Please RSVP.

http://doodle.com/poll/5hntc5hcwxsz2mx6

**Comment by yunong** [comment]
cc @mhdawson @seabaylea

**Comment by mhdawson** [comment]
@davepacheco I agree with the general discussion you outlined.  In our impromptu meeting at node interactive we discussed:

1) providing documentation on the format of the data needed by IBM's IDDE tool
2) providing documentation on the format of the data needed by mdb
3) reviewing the 2 of those to see if we could define a consolidated format that could be used by "any" tool and for which the required data would be included in node core files.

The focus being on the common "enablers" that allow tools to work on the community node releases.

**Comment by seabaylea** [comment]
Hey @yunong Unfortunately I'm on vacation for the next two weeks, so most likely can't make the next meeting.

Below are my notes from some of the discussions that occurred around Node Interactive. I wrote them up at the time to circulate more widely, but didn't get around to posting them earlier.

These all centre around memory issues and the V8 heapdump:

#### V8 Heapdump improvements:
1. Dump writing performance
   1. Reported as being much slower that expected - are they failing to use buffered writes?
   2. Uses large amounts of memory - are they building an in-memory model before writing to disk?
2. Dump creation capabilities
   1. Dump on OOM
   2. Dump on request
   3. Dump on triggers?
3. Dump contents
   1. Do we have sufficient data for analysis?
   2. Where is the format specified?

#### Chrome Dev Tools:
1. Not able to load large dumps
2. Sizes may be incorrect
3. Retained size may cross a closure boundary

There was also some conversations with @ofrobots who believe that the V8 team would be pretty receptive to heap dump improvements.

I'd love to see the automatic generation of heap dumps on memory exhaustion as a near term goal!

**Comment by yunong** [comment]
From the looks of it 12 PM PST on January 28, 2016 is the time that works for everyone. Let's plan on having the meeting there. I will update this thread with a hangouts link.

**Comment by yunong** [comment]
Here's the link to the hangout for active participants: 
https://plus.google.com/hangouts/_/event/c8619gosgi8sv1i0vo0dvnm0s04?hl=en-GB&authuser=0

**Comment by indutny** [comment]
Wow... I have a sudden conflict with CTC meeting. Sorry!

**Comment by yunong** [comment]
Meeting minutes: https://docs.google.com/document/d/1f7bGNEEahS9bIielk5sMpPRDlrMt3NtI2-GSHanNBcs/edit?usp=sharing

**Comment by mhdawson** [comment]
Sorry I had the same CTC conflict.  Looks like there was good progress on moving towards a common format.  I'll catch up with Richard to get up to speed.

**Comment by lucamaraschi** [comment]
@yunong was the meeting also recorded?

**Comment by yunong** [comment]
@lucamaraschi Unfortunately I couldn't figure out how to start the recording. I will try and make sure we record the next one.
